{% set name = "gromacswrapper" %}
{% set version = "0.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GromacsWrapper-{{ version }}.tar.gz
  sha256: b76a189497784a14f2bb7585ef04a4f257babf4c4445f33828fdfbbc2f78302c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numkit
    - numpy >=1.0
    - python >=3.6
    - six

test:
  imports:
    - gromacs
    - gromacs.fileformats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Becksteinlab/GromacsWrapper
  summary: A python wrapper around the Gromacs tools.
  doc_url: https://pythonhosted.org/GromacsWrapper/
  dev_url: https://github.com/Becksteinlab/GromacsWrapper
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    GromacsWrapper is a Python package that wraps system calls to GROMACS
    tools into thin classes. This allows for fairly seamless integration
    of the GROMACS tools into Python scripts.

extra:
  recipe-maintainers:
    - njzjz
